---
- hosts: localhost
  tasks:
  - name: stop the existing container
    command: docker stop mywebapp-container
    ignore_errors: yes
 
  - name: remove the existing container
    command: docker rm mywebapp-container
    ignore_errors: yes
 
  - name: remove the existing image
    command: docker rmi kieuahn/my-tomcat-app:final-version-2025b
    ignore_errors: yes
 
  - name: create docker container by using the image on Dockerhub
    command: docker run -d --name mywebapp-container -p 8083:8080 <name>/myapp:latest

